spring:
  #配置ShardingSphere
  shardingsphere:
    #配置ShardingSphere数据源
    datasource:
      #定义多个数据源名称
      names: ds1
      #配置数据源（可以配置多个）
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource #druid数据源
        driver-class-name: com.mysql.jdbc.Driver #如果是mysql8则这里要改变
        url: jdbc:mysql://localhost:3306/orderdb1?useSSL=false&autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root #mysql账号
        password: 18420163207 #mysql密码
    #开启ShardingSphere的SQL输出日志
    props:
      sql:
        show: true